config/routes.rb
Rails.application.routes.draw do
  resources :villages
  resources :wards
  resources :divisions
  resources :districts
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :district
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[ show edit update destroy ]

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: "Division was successfully created." }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to division_url(@division), notice: "Division was successfully updated." }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy!

    respond_to do |format|
      format.html { redirect_to divisions_url, notice: "Division was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def division_params
      params.require(:division).permit(:division_name, :district_id)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong>Division name:</strong>
    <%= division.division_name %>
  </p>

  <p>
    <strong>District:</strong>
    <%= division.district_id %>
  </p>

</div>

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :division_name, style: "display: block" %>
    <%= form.text_field :division_name %>
  </div>

  <div>
    <%= form.label :district_id, style: "display: block" %>
    <%= form.text_field :district_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Show this division", @division %> |
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Divisions</h1>

<div id="divisions">
  <% @divisions.each do |division| %>
    <%= render division %>
    <p>
      <%= link_to "Show this division", division %>
    </p>
  <% end %>
</div>

<%= link_to "New division", new_division_path %>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @division %>

<div>
  <%= link_to "Edit this division", edit_division_path(@division) %> |
  <%= link_to "Back to divisions", divisions_path %>

  <%= button_to "Destroy this division", @division, method: :delete %>
</div>