config/routes.rb
Rails.application.routes.draw do
  resources :villages
  resources :wards
  resources :divisions
  resources :districts
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/village.rb
class Village < ApplicationRecord
  belongs_to :ward
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  before_action :set_village, only: %i[ show edit update destroy ]

  # GET /villages or /villages.json
  def index
    @villages = Village.all
  end

  # GET /villages/1 or /villages/1.json
  def show
  end

  # GET /villages/new
  def new
    @village = Village.new
  end

  # GET /villages/1/edit
  def edit
  end

  # POST /villages or /villages.json
  def create
    @village = Village.new(village_params)

    respond_to do |format|
      if @village.save
        format.html { redirect_to village_url(@village), notice: "Village was successfully created." }
        format.json { render :show, status: :created, location: @village }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villages/1 or /villages/1.json
  def update
    respond_to do |format|
      if @village.update(village_params)
        format.html { redirect_to village_url(@village), notice: "Village was successfully updated." }
        format.json { render :show, status: :ok, location: @village }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villages/1 or /villages/1.json
  def destroy
    @village.destroy!

    respond_to do |format|
      format.html { redirect_to villages_url, notice: "Village was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_village
      @village = Village.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def village_params
      params.require(:village).permit(:village_name, :ward_id)
    end
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_form.html.erb
<%= form_with(model: village) do |form| %>
  <% if village.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
        <% village.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :village_name, style: "display: block" %>
    <%= form.text_field :village_name %>
  </div>

  <div>
    <%= form.label :ward_id, style: "display: block" %>
    <%= form.text_field :ward_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/villages/_village.html.erb
<div id="<%= dom_id village %>">
  <p>
    <strong>Village name:</strong>
    <%= village.village_name %>
  </p>

  <p>
    <strong>Ward:</strong>
    <%= village.ward_id %>
  </p>

</div>

app/views/villages/edit.html.erb
<h1>Editing village</h1>

<%= render "form", village: @village %>

<br>

<div>
  <%= link_to "Show this village", @village %> |
  <%= link_to "Back to villages", villages_path %>
</div>

app/views/villages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Villages</h1>

<div id="villages">
  <% @villages.each do |village| %>
    <%= render village %>
    <p>
      <%= link_to "Show this village", village %>
    </p>
  <% end %>
</div>

<%= link_to "New village", new_village_path %>

app/views/villages/new.html.erb
<h1>New village</h1>

<%= render "form", village: @village %>

<br>

<div>
  <%= link_to "Back to villages", villages_path %>
</div>

app/views/villages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @village %>

<div>
  <%= link_to "Edit this village", edit_village_path(@village) %> |
  <%= link_to "Back to villages", villages_path %>

  <%= button_to "Destroy this village", @village, method: :delete %>
</div>