config/routes.rb
Rails.application.routes.draw do
  resources :villages
  resources :wards
  resources :divisions
  resources :districts
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :region
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: %i[ show edit update destroy ]

  # GET /districts or /districts.json
  def index
    @districts = District.all
  end

  # GET /districts/1 or /districts/1.json
  def show
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts or /districts.json
  def create
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to district_url(@district), notice: "District was successfully created." }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1 or /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to district_url(@district), notice: "District was successfully updated." }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1 or /districts/1.json
  def destroy
    @district.destroy!

    respond_to do |format|
      format.html { redirect_to districts_url, notice: "District was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def district_params
      params.require(:district).permit(:district_name, :region_id)
    end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_district.html.erb
<div id="<%= dom_id district %>">
  <p>
    <strong>District name:</strong>
    <%= district.district_name %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= district.region_id %>
  </p>

</div>

app/views/districts/_form.html.erb
<%= form_with(model: district) do |form| %>
  <% if district.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
        <% district.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :district_name, style: "display: block" %>
    <%= form.text_field :district_name %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing district</h1>

<%= render "form", district: @district %>

<br>

<div>
  <%= link_to "Show this district", @district %> |
  <%= link_to "Back to districts", districts_path %>
</div>

app/views/districts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Districts</h1>

<div id="districts">
  <% @districts.each do |district| %>
    <%= render district %>
    <p>
      <%= link_to "Show this district", district %>
    </p>
  <% end %>
</div>

<%= link_to "New district", new_district_path %>

app/views/districts/new.html.erb
<h1>New district</h1>

<%= render "form", district: @district %>

<br>

<div>
  <%= link_to "Back to districts", districts_path %>
</div>

app/views/districts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @district %>

<div>
  <%= link_to "Edit this district", edit_district_path(@district) %> |
  <%= link_to "Back to districts", districts_path %>

  <%= button_to "Destroy this district", @district, method: :delete %>
</div>