config/routes.rb
Rails.application.routes.draw do
  resources :villages
  resources :wards
  resources :divisions
  resources :districts
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :division
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: %i[ show edit update destroy ]

  # GET /wards or /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1 or /wards/1.json
  def show
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards or /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to ward_url(@ward), notice: "Ward was successfully created." }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1 or /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to ward_url(@ward), notice: "Ward was successfully updated." }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1 or /wards/1.json
  def destroy
    @ward.destroy!

    respond_to do |format|
      format.html { redirect_to wards_url, notice: "Ward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ward_params
      params.require(:ward).permit(:ward_name, :division_id)
    end
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_with(model: ward) do |form| %>
  <% if ward.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
        <% ward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ward_name, style: "display: block" %>
    <%= form.text_field :ward_name %>
  </div>

  <div>
    <%= form.label :division_id, style: "display: block" %>
    <%= form.text_field :division_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wards/_ward.html.erb
<div id="<%= dom_id ward %>">
  <p>
    <strong>Ward name:</strong>
    <%= ward.ward_name %>
  </p>

  <p>
    <strong>Division:</strong>
    <%= ward.division_id %>
  </p>

</div>

app/views/wards/edit.html.erb
<h1>Editing ward</h1>

<%= render "form", ward: @ward %>

<br>

<div>
  <%= link_to "Show this ward", @ward %> |
  <%= link_to "Back to wards", wards_path %>
</div>

app/views/wards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wards</h1>

<div id="wards">
  <% @wards.each do |ward| %>
    <%= render ward %>
    <p>
      <%= link_to "Show this ward", ward %>
    </p>
  <% end %>
</div>

<%= link_to "New ward", new_ward_path %>

app/views/wards/new.html.erb
<h1>New ward</h1>

<%= render "form", ward: @ward %>

<br>

<div>
  <%= link_to "Back to wards", wards_path %>
</div>

app/views/wards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ward %>

<div>
  <%= link_to "Edit this ward", edit_ward_path(@ward) %> |
  <%= link_to "Back to wards", wards_path %>

  <%= button_to "Destroy this ward", @ward, method: :delete %>
</div>